// Test generated by RoostGPT for test ballot-go-test using AI Type Open Source AI and AI Model meta-llama/Llama-2-13b-chat

package test

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestHttpClientRequestSuccessful(t *testing.T) {
	// Arrange
	hostAddr := "example.com"
	command := "/path"
	params := bytes.NewBufferString(`{"key": "value"}`)

	expectedStatusCode := http.StatusOK
	expectedBody := `[{ "key": "value"}]`

	// Act
	statusCode, body, err := httpClientRequest(http.MethodGet, hostAddr, command, params)

	// Assert
	require.NoError(t, err)
	require.Equal(t, expectedStatusCode, statusCode)
	require.JSONEq(t, expectedBody, body)
}

func TestHttpClientRequestFailure(t *testing.T) {
	// Arrange
	hostAddr := "example.com"
	command := "/path"
	params := bytes.NewBufferString(`{"key": "value"}`)

	errMessage := "Some error message"

	// Act
	statusCode, body, err := httpClientRequest(http.MethodGet, hostAddr, command, params)

	// Assert
	require.Error(t, err)
	require.Equal(t, http.StatusBadRequest, statusCode)
	require.Contains(t, body, errMessage)
}
