// Test generated by RoostGPT for test roost-test using AI Type Open Source AI and AI Model meta-llama/Llama-2-13b-chat

package vote_test

import (
	"testing"

	"github.com/stretchr/testify/require"
)

type Vote struct {
	CandidateID int
	Option      string
}

func TestSaveVoteSuccess(t *testing.T) {
	// Arrange
	candidateVotesStore := map[int]int{
		1: 0,
		2: 0,
	}
	vote := Vote{
		CandidateID: 1,
		Option:     "option1",
	}

	// Act
	err := saveVote(vote)

	// Assert
	require.NoError(t, err)
	require.Equal(t, 1, candidateVotesStore[1])
	require.Equal(t, 0, candidateVotesStore[2])
}

func TestSaveVoteFailure(t *testing.T) {
	// Arrange
	candidateVotesStore := map[int]int{
		1: 0,
		2: 0,
	}
	vote := Vote{
		CandidateID: 2,
		Option:     "option1",
	}

	// Act
	err := saveVote(vote)

	// Assert
	require.Error(t, err)
	require.Equal(t, 0, candidateVotesStore[1])
	require.Equal(t, 1, candidateVotesStore[2])
}
