// Test generated by RoostGPT for test roost-test using AI Type Open Source AI and AI Model meta-llama/Llama-2-13b-chat

package test_serve_root

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestServeRoot(t *testing.T) {
	// Test case 1: Successful GET request
	req, _ := http.NewRequest(http.MethodGet, "/", bytes.NewBufferString(""))
	rr := &http.Recorder{}
	serveRoot(rr, req)
	assert.Equal(t, http.StatusOK, rr.Result().StatusCode)
	respBytes, _ := ioutil.ReadAll(rr.Body)
	var resp map[string]interface{}
	json.Unmarshal(respBytes, &resp)
	assert.Equal(t, "result request received", string(resp["message"].([]byte)))

	// Test case 2: Invalid POST request
	req, _ := http.NewRequest(http.MethodPost, "/", bytes.NewBufferString("{\"candidateID\": \"\"}"))
	rr := &http.Recorder{}
	serveRoot(rr, req)
	assert.Equal(t, http.StatusBadRequest, rr.Result().StatusCode)
	assert.Contains(t, rr.Body.String(), "Vote is not valid. Vote can not be saved")
}
